[package]
name = "solidcpp"
version = "0.1.2"
edition = "2021"

[dependencies]
hashbrown = "0.15.1"
byteorder = "1.5.0"
clap = { version = "4.0.3", features = ["derive"] }
ethereum-types = "0.15.1"
globwalk = "0.9.1"
hex = "0.4.3"
regex = "1.11.0"
serde_json = "1.0"
sha3 = "0.10.8"
